name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN:
    description: 'The GitHub token to use for authentication'
    required: true
  ports:
    description: 'Ports to expose, separated by comma'
    required: true
outputs:
  url-1:
    description: 'URL of the first exposed port'
    value: ${{ steps.expose-tunnel.outputs.url-1 }}
  url-2:
    description: 'URL of the second exposed port'
    value: ${{ steps.expose-tunnel.outputs.url-2 }}
  url-3:
    description: 'URL of the third exposed port'
    value: ${{ steps.expose-tunnel.outputs.url-3 }}
  url-4:
    description: 'URL of the fourth exposed port'
    value: ${{ steps.expose-tunnel.outputs.url-4 }}
  url-5:
    description: 'URL of the fifth exposed port'
    value: ${{ steps.expose-tunnel.outputs.url-5 }}
runs:
  using: "composite"
  steps:
    - name: Add info about starting new preview
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        number: ${{ github.event.issue.number || github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        message: |
          **🖼️ Preview Environment:** _Starting..._

    - name: Extract current commit
      id: sha
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          const { owner, repo, number: pull_number } = context.issue;
          const pr = await github.rest.pulls.get({
            owner,
            repo,
            pull_number,
          });
          return pr.data.head.ref
    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.sha.outputs.result }}

    - name: Start frontend tunnel
      id: expose-tunnel
      uses: Rei-x/expose-localtunnel-action@main
      with:
        ports: ${{ inputs.ports }}


