name: Preview

on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
      triggered_by_ci: ${{ steps.check.outputs.triggered_by_ci }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./comment
        id: check
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

  run-preview:
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ needs.check.outputs.triggered == 'true' }}
    concurrency:
      group: ${{ github.event.issue.number || github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./start-preview
        id: tunnel-url
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          ports: 3000

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Add info about dependency install
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Installing dependencies..._

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Add info about starting app
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Starting app..._
      - name: Starting app
        run: npx serve -l 3000 &

      - name: go up
        run: cd ..

      - uses: ./end-preview
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          url: ${{ steps.tunnel-url.outputs.url-1 }}

